cloudgate:
  required_version: '~> 11.0.1'
app:
  name: light-bikes
  users:
    dhyer: {}
    rnorton: {}
  load_balancers:
    web:
      ssl_cert_arn: "arn:aws:acm:us-west-2:830473435438:certificate/b119c8b6-9305-4532-9798-dcfbf712158b"
  instance_pools:
    web:
      http_port: 8080
      health_check_path: /health-check
      instance_type: t3.small
      max_size: 1
      min_size: 1
      env_vars:
        LOG_LEVEL: 'info'
        UI_CORS_URL: http://light-bikes-ui.s3-website-us-west-2.amazonaws.com/
